name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: 'ssh-keyscan ${{ secrets.SERVER_URL }} >> ~/.ssh/known_hosts'
      - run: yarn
      - run: git checkout yarn.lock
      - run: SERVER_URL=${{ secrets.SERVER_URL }} USER=${{ secrets.USER }} yarn deploy
