name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy cm.com
    runs-on: ubuntu-latest

    # TODO: Fix this shit, but it's faster this way
    # needs: build

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd todo_app
            sh run_deploy.sh
